### ISSUE TITLE
How to loop throught redis and remove connection?

### ISSUE THREAD

**Issue by Gobakabana** [lyzerk/medium#1]
Hello, 

Could you provide some example to loop through redis and delete user afte some time?

I have implement your exemple but i'm stuck at this point. 

Thank a lot !

**Comment by lyzerk** [comment]
Hello,

Could you tell me your condition ? What do you mean with 'Some time' ? If it is a specific time, you should use 'expire'. Otherwise you can remove it manually. e.g. https://stackexchange.github.io/StackExchange.Redis/KeysValues#values

Thanks

**Comment by Gobakabana** [comment]
I use SignalR for publish/subscribe and I use Redis to scale with load balancer. 
In your code you have a RemoveUser method which is set exitTime to date now.
` 
       public void RemoveUser(string connectionId)
        {
            // I didn't remove the client from the collection for see the exit date
            if (_users.TryGetValue(connectionId, out var client))
                client.ExitTime = DateTime.Now;
        }`

And Heartbeat set latestPing for connectionId

How to remove old connection maybe after certain time (5 or 10 min) , do i need to store clientlist to redis  ? If yes where to put the loop through key/value from redis to delete old connection.

In fact I just follow your guide and it says :

> So, now we know latest client ping time. We can loop through the redis and if we didn’t receive a ping at least 5 min. from a client, we can remove it. The control time should be depend on your reconnecting time span settings. Because a re-connection might have happened after a natural disconnection case.

thx :)

**Comment by lyzerk** [comment]
I think you can handle it in a scheduled job like Hangfire or Quartz. Quartz would be better for a simple approach.
You may follow this guide https://andrewlock.net/creating-a-quartz-net-hosted-service-with-asp-net-core/. Define a Job scheduler with a cron expression and do the cleaning.

Thank you

**Comment by Gobakabana** [comment]
Well ok , but when I set KEYS * redis says it empty.

In createUser method I think I need to store the connectionId on redis right ? And in Heartbeat update with lastping. 

In second time in quartz I deleted the old connection.

Is it the right way ?

**Comment by lyzerk** [comment]
Absolutely right !
